name: Keep notevault Alive

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping notevault
        run: |
          for i in 1 2 3; do
            curl -s https://note-vault-335l.onrender.com/ > /dev/null && break
            sleep 10
          done
